# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('ЭРУ', 'ЭРУ'), ('ГШУ', 'ГШУ'), ('ГРП', 'ГРП'), ('связи', 'связи'), ('ППС', 'ППС'), ('энергетический', 'энергетический'), ('ЛЭУ', 'ЛЭУ'), ('ИЭТЛ', 'ИЭТЛ'), ('ВСП', 'ВСП'), ('котельные', 'котельные')], max_length=20, verbose_name='участок')),
                ('tipe', models.CharField(choices=[('пояс монтажный', 'пояс монтажный'), ('пояс страховочный', 'пояс страховочный'), ('веревка', 'веревка')], max_length=20, verbose_name='тип')),
                ('number', models.IntegerField(verbose_name='количество')),
                ('data', models.DateField(verbose_name='срок сдачи')),
            ],
            options={
                'verbose_name': 'пояс',
                'verbose_name_plural': 'поясов',
            },
        ),
    ]
