# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='номер по порядку')),
                ('title', models.CharField(blank=True, max_length=40, verbose_name='название бланка')),
                ('document', models.CharField(blank=True, max_length=40, verbose_name='документ-основание')),
                ('doc', models.CharField(blank=True, max_length=10, verbose_name='ссылка на doc')),
                ('pdf', models.CharField(blank=True, max_length=10, verbose_name='ссылка на pdf')),
            ],
            options={
                'verbose_name': 'бланк',
                'verbose_name_plural': 'бланки',
            },
        ),
    ]
